### ISSUE TITLE
Create & Configure CI build

### ISSUE THREAD

**Issue by tsimbalar** [serilog-archive/serilog-settings-combined#2]
To build PRs and commits on dev

**Comment by nblumhardt** [comment]
I've turned on CI via AppVeyor at: https://ci.appveyor.com/project/serilog/serilog-settings-combined

Just including the Build.ps1 and appveyor.yml files from another (current) Serilog repository will be enough to get things building/publishing 👍

**Comment by tsimbalar** [comment]
@nblumhardt thanks, will look into this .... I have never user AppVeyor and I haven't done any .NET Core so far, so I'm expecting to learn a few tricks, here 😉

**Comment by tsimbalar** [comment]
Yay ! 

https://ci.appveyor.com/project/serilog/serilog-settings-combined/build/1

@nblumhardt  thanks, the existing scripts and config file are a great base :) This looks rock solid !

**Comment by tsimbalar** [comment]
Closing it because I believe I'm done, but if a second pair of eyes can check that I didn't do anything stupid :)
